FROM golang:1.27-bookworm AS go

FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
    && apt-get install -y docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY --from=go /usr/local/go /usr/local/go

ENV PATH="/usr/local/go/bin:${PATH}"


COPY plugins.txt /usr/share/jenkins/plugins.txt

RUN jenkins-plugin-cli --plugin-file=/usr/share/jenkins/plugins.txt

RUN usermod -aG root jenkins

USER jenkins