FROM jenkins/jenkins:lts

USER root

RUN apt-get update \
    && apt-get install -y docker.io \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY plugins.txt /usr/share/jenkins/plugins.txt

USER jenkins

RUN jenkins-plugin-cli --plugin-file=/usr/share/jenkins/plugins.txt